Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -23,14 +23,14 @@ jobs:
       run: dotnet restore
     - name: Build
       run: dotnet build --no-restore
-    - name: Test
-      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
-    - name: Publish test results
-      uses: dorny/test-reporter@v1
-      if: success() || failure()
-      with:
-        name: "test results"
-        path: "**/TestResults/*.trx"
-        reporter: dotnet-trx
+#    - name: Test
+#      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
+#    - name: Publish test results
+#      uses: dorny/test-reporter@v1
+#      if: success() || failure()
+#      with:
+#        name: "test results"
+#        path: "**/TestResults/*.trx"
+#        reporter: dotnet-trx
     - name: Pack
       run: dotnet pack crypto
