Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -9,7 +9,7 @@ on:
 jobs:
   build:
 
-    runs-on: [self-hosted, windows, X64]
+    runs-on: windows-latest
 
     steps:
     - uses: actions/checkout@v2
@@ -22,17 +22,19 @@ jobs:
     - name: Restore dependencies
       run: dotnet restore
     - name: Build crypto
-      run: dotnet build crypto\src --no-restore
-    - name: Build tests
-      run: dotnet build crypto\test --no-restore
-    - name: Test
-      run: dotnet test crypto\test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
-    - name: Publish test results
-      uses: dorny/test-reporter@v1
-      if: success() || failure()
-      with:
-        name: "test results"
-        path: "**/TestResults/*.trx"
-        reporter: dotnet-trx
+      run: dotnet build crypto\src --no-restore --configuration Release
+#    - name: Build tests
+#      run: dotnet build crypto\test --no-restore --configuration Release
+#    - name: Test
+#      run: dotnet test crypto\test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" --configuration Release
+#    - name: Publish test results
+#      uses: dorny/test-reporter@v1
+#      if: success() || failure()
+#      with:
+#        name: "test results"
+#        path: "**/TestResults/*.trx"
+#        reporter: dotnet-trx
     - name: Pack
       run: dotnet pack crypto/src
+#    - name: Publish
+#      run: dotnet nuget push crypto/src/bin/Release/*.nupkg -s nuget.org -k ${{secrets.NUGET_TOKEN}}
