Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -23,23 +23,19 @@ jobs:
       run: dotnet build crypto/src --no-restore --configuration Release
     - name: Build tests
       run: dotnet build crypto/test --no-restore
-    - name: Run tests
-      run: dotnet test crypto/test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
-#    - name: Build
-#      run: dotnet build --no-restore --configuration Release
+#    - name: Run tests
+#      run: dotnet test crypto/test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
     - uses: actions/upload-artifact@master
       with:
         name: build-artifacts
         path: crypto/src/bin
-#    - name: Test
-#      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
-    - name: Publish test results
-      uses: dorny/test-reporter@v1
-      if: success() || failure()
-      with:
-        name: "test results"
-        path: "**/TestResults/*.trx"
-        reporter: dotnet-trx
+#    - name: Publish test results
+#      uses: dorny/test-reporter@v1
+#      if: success() || failure()
+#      with:
+#        name: "test results"
+#        path: "**/TestResults/*.trx"
+#        reporter: dotnet-trx
 
   publish:
     permissions:
@@ -50,6 +46,10 @@ jobs:
     - uses: actions/checkout@v2
       with:
         fetch-depth: 0
+    - name: Setup .NET
+      uses: actions/setup-dotnet@v1
+      with:
+        dotnet-version: 3.1.x
     - uses: actions/download-artifact@master
       with:
         name: build-artifacts
