Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -37,15 +37,16 @@ jobs:
 #    needs: build
 #    runs-on: windows-latest
 #    steps:
-    - name: Test
-      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
-    - name: Publish test results
-      uses: dorny/test-reporter@v1
-      if: success() || failure()
-      with:
-        name: "test results"
-        path: "**/TestResults/*.trx"
-        reporter: dotnet-trx
+
+#    - name: Test
+#      run: dotnet test --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx"
+#    - name: Publish test results
+#      uses: dorny/test-reporter@v1
+#      if: success() || failure()
+#      with:
+#        name: "test results"
+#        path: "**/TestResults/*.trx"
+#        reporter: dotnet-trx
 
   publish:
     permissions:
@@ -54,6 +55,10 @@ jobs:
     needs: build
     runs-on: windows-latest
     steps:
+    - name: Get artifacts
+      with:
+        name: "build"
+        path: "/crypto/src/**"
     - name: Pack
       run: dotnet pack crypto/src --configuration Release
     - name: Publish
